const BurgerActionTypes = {
	ADD_INGREDIENT: 'ADD_INGREDIENT',
	REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
	FETCH_INGREDIENTS_START: 'FETCH_INGREDIENTS_START',
	FETCH_INGREDIENTS_SUCCESS: 'FETCH_INGREDIENTS_SUCCESS',
	FETCH_INGREDIENTS_FAILURE: 'FETCH_INGREDIENTS_FAILURE'
};

export default BurgerActionTypes;
